---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/
      #,http://localhost:8013/eureka/
---
spring:
  profiles: First
  application:
    name: naming-server
server:
  port: 8011  
eureka:  
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: 
        - http://localhost:8012/eureka/
        #,http://localhost:8013/eureka/

---
spring:
  profiles: Second
  application:
    name: naming-server    
server:
  port: 8012
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true        
    serviceUrl:
      defaultZone: 
        - http://localhost:8011/eureka/
        #,http://localhost:8011/eureka/

#  ---
#spring:
#  profiles: Third
#  application:
#    name: naming-server     
#server:
#  port: 8013
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true    
#    serviceUrl:
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/      
